name: assignment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_ui_auth: ^1.1.9
  google_sign_in: ^5.4.3
  firebase_ui_oauth_google: ^1.0.16
  firebase_dynamic_links: ^5.0.11
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
