// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBySKStkJZ55UMr1tNXyNTZqhz0poIBXGM',
    appId: '1:124292595185:android:78f104baa4aeaa3ca2d850',
    messagingSenderId: '124292595185',
    projectId: 'assignment-pepcorns',
    storageBucket: 'assignment-pepcorns.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVoHwSGGLeYAPP4jHplXxsHh6VyhdwSak',
    appId: '1:124292595185:ios:e266705785039136a2d850',
    messagingSenderId: '124292595185',
    projectId: 'assignment-pepcorns',
    storageBucket: 'assignment-pepcorns.appspot.com',
    androidClientId: '124292595185-35f1dhdh2739t1h71ekppkr5bsigih7u.apps.googleusercontent.com',
    iosClientId: '124292595185-2ac12l9unlgg23bo544aopa44576irou.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );
}
